--@diagnostic disable: undefined-global
----------------------------------------------------------------------------------------------------
vim.cmd("hi clear")
vim.g.colors_name = "ares"
local hi = function(name, val)
	val.cterm = val.cterm or {}
	vim.api.nvim_set_hl(0, name, val)
end

local background = "#111111"
local foreground = "#BFC6C4"

local comment = "#2e2e2e"
local error_fg = "#000000"
local error_bg = "#ff3500"

hi("Normal", { bg = background, fg = foreground })
hi("Cursor", { bg = "#E6501B" })
-- hi("String", { fg = "#0C7779" })
hi("String", { fg = "#8B7355" })
hi("Character", { link = "Special" })
hi("Number", { fg = "#B66149" })
hi("Float", { link = "Number" })
hi("Boolean", { fg = "#A45B5E", bold = true })
hi("Constant", { fg = "#C14D30", bold = true })
hi("Identifier", { fg = "#00af74" })
hi("Keyword", { fg = "#813405", bold = true })
hi("Operator", { fg = "#CC561E" })
hi("Special", { fg = "#C14D30", bold = true })
hi("Delimiter", { link = "Operator" })
hi("Type", { fg = "#D53E0F", bold = true })
hi("Function", { fg = "#E76F2E", bold = true })
hi("Variable", { fg = "#6E5034", bold = true })
hi("Label", { link = "Statement" })
hi("MsgArea", { fg = foreground })

hi("Visual", { fg = "#C40C0C", bg = "#FF6500", bold = true })
hi("Search", { link = "Visual" })
hi("Substitute", { bg = "#ffffff", fg = "#000000" })
hi("IncSearch", { bg = "#ffffff", fg = "#000000" })
hi("CurSearch", { link = "IncSearch" })
hi("hlsearch", { link = "Visual" })

hi("Macro", { fg = "#C14D30", bold = true })
hi("Added", { fg = "#777777" })
hi("Changed", { fg = "#999999" })
hi("Removed", { fg = "#F11122" })
hi("yanking", { bg = foreground })
hi("TODO", { bg = "#D53E0F" })
hi("Comment", { fg = comment })

hi("Title", { fg = "#118599" })
hi("TelescopeBorder", { fg = foreground, bg = background })
hi("TelescopeMatching", { link = "Boolean" })
hi("Pmenu", { bg = "#454140", fg = "#ffffff" })
hi("CursorLine", { bg = "#1f1f1f", })
hi("CursorLineNr", { bg = background, fg = "#babaff", bold = true })
hi("LineNr", { bg = background, fg = "#29332f" })

hi("cTypedef", { link = "Identifier" })
hi("cStructure", { link = "Special" })
hi("cParen", { fg = "#C08552", bold = true })
hi("cBracket", { link = "Operator", bold = true })
hi("cBlock", { link = "cParen" })
hi("cFormat", { link = "Variable" })
hi("cDefine", { link = "PreProc" })

--hi("LineNrAbove", {})
--hi("LineNrBelow", {})

hi("@lsp.type.c", { link = "Type" })
hi("@lsp.type.macro.c", { link = "Macro" })
hi("@lsp.type.parameter.c", { link = "Variable" })
hi("@lsp.type.function.c", { link = "Function" })
hi("@lsp.type.variable.c", { link = "Variable" })
hi("@lsp.type.bracket.c", { fg = "#C08552" })
hi("@lsp.type.property.c", { fg = "#9c6615" })
hi("@lsp.type.label.c", { link = "Label" })

hi("@lsp.type.punctuation.c", { link = "Operator" })
hi("@lsp.typemod.punctuation.c", { link = "Operator" })
hi("@lsp.type.operator.c", { link = "Operator" })
hi("@lsp.typemod.operator.c", { link = "Operator" })

hi("PreProc", { fg = "#E87F24" })
hi("cInclude", { link = "PreProc" })
hi("cConstant", { link = "cInclude" })
hi("@variable", { link = "Variable" })

hi("@spell.markdown", { link = "Spell" })
hi("@markup.heading.3.markdown", { link = "Keyword" })
hi("@markup.heading.3.markdown", { link = "Keyword" })
hi("@markup.raw.block.markdown", { link = "String" })

hi("Typedef", { link = "Special" })
hi("Statement", { link = "Keyword" })
hi("Structure", { link = "Typedef" })


hi("PmenuSel", { link = "Visual" })
hi("PmenuExtra", { link = "Visual" })
hi("PmenuExtraSel", { link = "PmenuSel" })
hi("PmenuKind", { link = "Visual" })
hi("PmenuKindSel", { link = "PmenuSel" })
hi("PmenuSbar", { link = "CursorLine" })
hi("PmenuThumb", { link = "Boolean" })

--error msgs and warnings
hi("Underlined", { underline = true, fg = error_bg })
hi("DiagnosticError", { bg = error_bg, fg = error_fg, bold = true })
hi("Error", { bg = "#9F0e21", fg = "#0f0f0f" })
hi("ErrorMsg", { bg = "#9F0e21", fg = "#0f0f0f", bold = true })
hi("WarningMsg", { bg = "#ef6400", fg = "#0f0f0f", bold = true })

hi("CursorColumn", { bg = "#9f1f1f" })
hi("CursorIM", { link = "Cursor" })
hi("CursorLineFold", { link = "FoldColumn" })
hi("CursorLineSign", { link = "SignColumn" })

hi("NormalFloat", { link = "Normal" })
hi("FloatBorder", { link = "NormalFloat" })
hi("FloatFooter", { link = "Boolean" })
hi("FloatShadow", { link = "NormalFloat" })
hi("FloatShadowThrough", { link = "FloatShadow" })
hi("FloatTitle", { link = "Title" })
hi("WinSeparator", { link = "Identifier" })
hi("NormalNC", {})
hi("RedrawDebugNormal", { reverse = true })

hi("NvimInvalidString", { link = "Error" })
hi("NvimInvalidStringBody", { link = "Underlined" })
hi("NvimInvalidStringQuote", { link = "Underlined" })
hi("NvimInvalidStringSpecial", { link = "Underlined" })
hi("NvimString", { link = "String" })
hi("NvimStringBody", { link = "NvimString" })
hi("NvimStringQuote", { link = "NvimString" })
hi("NvimStringSpecial", { link = "Special" })

hi("NvimInvalidNumber", { link = "Error" })
hi("NvimInvalidNumberPrefix", { link = "Error" })
hi("NvimNumber", { link = "Number" })
hi("NvimNumberPrefix", { link = "Boolean" })

hi("ColorColumn", {})
hi("Conceal", {})
hi("Conditional", { link = "Statement" })
hi("Debug", {})
hi("Define", { link = "PreProc" })
hi("DiagnosticDeprecated", {})
hi("DiagnosticFloatingError", { link = "Error" })
hi("DiagnosticFloatingHint", { link = "WarningMsg" })
hi("DiagnosticFloatingInfo", { link = "Pmenu" })
hi("DiagnosticFloatingOk", { link = "Visual" })
hi("DiagnosticFloatingWarn", { link = "WarningMsg" })
hi("DiagnosticHint", { link = "WarningMsg" })
hi("DiagnosticInfo", { link = "Pmenu" })
hi("DiagnosticOk", { link = "Visual" })
hi("DiagnosticSignError", { link = "Error" })
hi("DiagnosticSignHint", { link = "Boolean" })
hi("DiagnosticSignInfo", { link = "Comment" })
hi("DiagnosticSignOk", { link = "Normal" })
hi("DiagnosticSignWarn", { link = "WarningMsg" })
hi("DiagnosticUnderlineError", { link = "Underlined" })
hi("DiagnosticUnderlineHint", {})
hi("DiagnosticUnderlineInfo", {})
hi("DiagnosticUnderlineOk", {})
hi("DiagnosticUnderlineWarn", {})
hi("DiagnosticUnnecessary", { link = "Comment" })
hi("DiagnosticVirtualTextError", { link = "Error" })
hi("DiagnosticVirtualTextHint", { link = "Comment" })
hi("DiagnosticVirtualTextInfo", { link = "Comment" })
hi("DiagnosticVirtualTextOk", { link = "Normal" })
hi("DiagnosticVirtualTextWarn", { link = "WarningMsg" })
hi("DiagnosticWarn", { link = "WarningMsg" })
hi("DiffAdd", { link = "Added" })
hi("DiffChange", { link = "Changed" })
hi("DiffDelete", { link = "Removed" })
hi("DiffText", { link = "Boolean" })
hi("Directory", { link = "Title" })
hi("EndOfBuffer", { link = "Normal" })
hi("ErrorMsg", { link = "Error" })
hi("Exception", { link = "Boolean" })
hi("FoldColumn", {})
hi("Folded", {})
hi("Ignore", {})
hi("Include", { link = "PreProc" })
hi("LspCodeLens", {})
hi("LspCodeLensSeparator", { link = "CursorLine" })
hi("LspInfoBorder", { link = "Identifier" })
hi("LspInfoFiletype", {})
hi("LspInfoList", {})
hi("LspInfoTip", {})
hi("LspInfoTitle", { link = "Title" })
hi("LspInlayHint", {})
hi("LspReferenceRead", {})
hi("LspReferenceText", {})
hi("LspReferenceWrite", {})
hi("LspSignatureActiveParameter", {})
hi("MatchParen", { link = "Special" })
hi("ModeMsg", { link = "ModeMsg" })
hi("MoreMsg", { link = "Special" })
hi("MsgSeparator", { link = "CursorLine" })
hi("NonText", {})
hi("NvimAnd", {})
hi("NvimArrow", {})
hi("NvimAssignment", {})
hi("NvimAssignmentWithAddition", {})
hi("NvimAssignmentWithConcatenation", {})
hi("NvimAssignmentWithSubtraction", {})
hi("NvimAugmentedAssignment", {})
hi("NvimBinaryMinus", {})
hi("NvimBinaryOperator", { link = "Operator" })
hi("NvimBinaryPlus", {})
hi("NvimCallingParenthesis", { link = "Operator" })
hi("NvimColon", {})
hi("NvimComma", {})
hi("NvimComparison", {})
hi("NvimComparisonModifier", {})
hi("NvimConcat", {})
hi("NvimConcatOrSubscript", {})
hi("NvimContainer", {})
hi("NvimCurly", {})
hi("NvimDict", {})
hi("NvimDivision", {})
hi("NvimDoubleQuote", {})
hi("NvimDoubleQuotedBody", {})
hi("NvimDoubleQuotedEscape", {})
hi("NvimDoubleQuotedUnknownEscape", {})
hi("NvimEnvironmentName", {})
hi("NvimEnvironmentSigil", {})
hi("NvimFigureBrace", {})
hi("NvimFloat", { link = "number" })
hi("NvimIdentifier", { link = "Identifier" })
hi("NvimIdentifierKey", {})
hi("NvimIdentifierName", {})
hi("NvimIdentifierScope", {})
hi("NvimIdentifierScopeDelimiter", {})
hi("NvimInternalError", {})
hi("NvimInvalid", {})
hi("NvimInvalidAnd", {})
hi("NvimInvalidArrow", {})
hi("NvimInvalidAssignment", {})
hi("NvimInvalidAssignmentWithAddition", {})
hi("NvimInvalidAssignmentWithConcatenation", {})
hi("NvimInvalidAssignmentWithSubtraction", {})
hi("NvimInvalidAugmentedAssignment", {})
hi("NvimInvalidBinaryMinus", {})
hi("NvimInvalidBinaryOperator", { link = "Error" })
hi("NvimInvalidBinaryPlus", {})
hi("NvimInvalidCallingParenthesis", {})
hi("NvimInvalidColon", {})
hi("NvimInvalidComma", {})
hi("NvimInvalidComparison", {})
hi("NvimInvalidComparisonModifier", {})
hi("NvimInvalidConcat", {})
hi("NvimInvalidConcatOrSubscript", {})
hi("NvimInvalidContainer", {})
hi("NvimInvalidCurly", {})
hi("NvimInvalidDelimiter", {})
hi("NvimInvalidDict", {})
hi("NvimInvalidDivision", {})
hi("NvimInvalidDoubleQuote", {})
hi("NvimInvalidDoubleQuotedBody", {})
hi("NvimInvalidDoubleQuotedEscape", {})
hi("NvimInvalidDoubleQuotedUnknownEscape", {})
hi("NvimInvalidEnvironmentName", {})
hi("NvimInvalidEnvironmentSigil", {})
hi("NvimInvalidFigureBrace", {})
hi("NvimInvalidFloat", {})
hi("NvimInvalidIdentifier", {})
hi("NvimInvalidIdentifierKey", {})
hi("NvimInvalidIdentifierName", {})
hi("NvimInvalidIdentifierScope", {})
hi("NvimInvalidIdentifierScopeDelimiter", {})
hi("NvimInvalidLambda", {})
hi("NvimInvalidList", {})
hi("NvimInvalidMod", {})
hi("NvimInvalidMultiplication", {})
hi("NvimInvalidNestingParenthesis", {})
hi("NvimInvalidNot", {})
hi("NvimInvalidOperator", { link = "Error" })
hi("NvimInvalidOptionName", {})
hi("NvimInvalidOptionScope", {})
hi("NvimInvalidOptionScopeDelimiter", {})
hi("NvimInvalidOptionSigil", {})
hi("NvimInvalidOr", {})
hi("NvimInvalidParenthesis", {})
hi("NvimInvalidPlainAssignment", {})
hi("NvimInvalidRegister", {})
hi("NvimInvalidSingleQuote", {})
hi("NvimInvalidSingleQuotedBody", {})
hi("NvimInvalidSingleQuotedQuote", {})
hi("NvimInvalidSingleQuotedUnknownEscape", {})
hi("NvimInvalidSpacing", {})
hi("NvimInvalidSubscript", {})
hi("NvimInvalidSubscriptBracket", {})
hi("NvimInvalidSubscriptColon", {})
hi("NvimInvalidTernary", {})
hi("NvimInvalidTernaryColon", {})
hi("NvimInvalidUnaryMinus", {})
hi("NvimInvalidUnaryOperator", { link = "Error" })
hi("NvimInvalidUnaryPlus", {})
hi("NvimInvalidValue", {})
hi("NvimLambda", {})
hi("NvimList", {})
hi("NvimMod", {})
hi("NvimMultiplication", {})
hi("NvimNestingParenthesis", {})
hi("NvimNot", {})
hi("NvimOperator", { link = "Operator" })
hi("NvimOptionName", {})
hi("NvimOptionScope", {})
hi("NvimOptionScopeDelimiter", {})
hi("NvimOptionSigil", {})
hi("NvimOr", {})
-- hi("NvimParenthesis", { link = "@punctuation.bracket" })
hi("NvimPlainAssignment", {})
hi("NvimRegister", {})
hi("NvimSingleQuote", {})
hi("NvimSingleQuotedBody", {})
hi("NvimSingleQuotedQuote", {})
hi("NvimSingleQuotedUnknownEscape", {})
hi("NvimSpacing", {})
hi("NvimSubscript", {})
hi("NvimSubscriptBracket", {})
hi("NvimSubscriptColon", {})
hi("NvimTernary", {})
hi("NvimTernaryColon", {})
hi("NvimUnaryMinus", {})
hi("NvimUnaryOperator", { link = "Operator" })
hi("NvimUnaryPlus", {})
hi("PreCondit", { link = "PreProc" })
hi("Question", {})
hi("QuickFixLine", { link = "Special" })
hi("RedrawDebugClear", {})
hi("RedrawDebugComposed", {})
hi("RedrawDebugRecompose", {})
hi("Repeat", { link = "Special" })
hi("SignColumn", { bg = background })
hi("SnippetTabstop", {})
hi("SpecialChar", { link = "Special" })
hi("SpecialComment", { link = "Special" })
hi("SpecialKey", { link = "Special" })
hi("SpellBad", { undercurl = true, fg = comment })
hi("SpellCap", { link = "Comment" })
hi("SpellLocal", { link = "Comment" })
hi("SpellRare", { link = "Comment" })
hi("StatusLine", {})
hi("StatusLineNC", {})
hi("StorageClass", { link = "Keyword" })
hi("TabLine", { link = "Normal" })
hi("TabLineFill", { link = "TabLine" })
hi("TabLineSel", { reverse = true })
hi("Tag", { link = "Keyword" })

hi("jsonstring", { link = "String" })
hi("jsonStringMatch", { link = "Special" })
hi("jsonfold", { link = "String" })

hi("VertSplit", { link = "Normal" })
hi("Whitespace", { fg = "none", bg = "none" })
hi("WildMenu", { link = "Pmenu" })
