#!/usr/bin/env bash
set -euo pipefail

DOTFILES="/devenv/repos/vsix8625/dotfiles"

ln -sf $DOTFILES/.bashrc ~/.bashrc
ln -sf $DOTFILES/.aliases ~/.aliases
ln -sf $DOTFILES/.clang-format ~/.clang-format

# Configs
mkdir -p ~/.config
ln -sf "$DOTFILES/nvim" ~/.config/
ln -sf "$DOTFILES/foot" ~/.config/
ln -sf "$DOTFILES/sway" ~/.config/
ln -sf "$DOTFILES/waybar" ~/.config/
ln -sf "$DOTFILES/swaylock" ~/.config/
