#!/usr/bin/env bash
set -euo pipefail

DOTFILES="/devenv/repos/vsix8625/dotfiles"

ln -sf $DOTFILES/.bashrc ~/.bashrc
ln -sf $DOTFILES/.aliases ~/.aliases
ln -sf $DOTFILES/.clang-format ~/.clang-format

# Configs
mkdir -p ~/.config
ln -sf $DOTFILES/nvim ~/.config/nvim
ln -sf "$DOTFILES/foot" ~/.config/foot
ln -sf "$DOTFILES/hypr" ~/.config/hypr
ln -sf "$DOTFILES/waybar" ~/.config/waybar
ln -sf "$DOTFILES/swaylock" ~/.config/swaylock
